version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - networks

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   volumes:
  #     - ./data/mongo:/data/db
  #     - ./data/mongo-init:/docker-entrypoint-initdb.d
  #   ports:
  #     - "27017:27017"
  # mongo-express:
  #   image: mongo-express:0.54
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: false
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

  api:
    build: .
    container_name: fastapi-application
    environment:
      MONGO_URL: mongodb://mongodb:27017/boilerplate
      PORT: 8000
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - networks
    restart: "no"
volumes:
  dbdata6:
networks:
  networks:
    driver: bridge
